/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'
import { Route as AuthenticatedLeconIdRouteImport } from './routes/_authenticated/lecon.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeconIdRoute = AuthenticatedLeconIdRouteImport.update({
  id: '/lecon/$id',
  path: '/lecon/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lecon/$id': typeof AuthenticatedLeconIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lecon/$id': typeof AuthenticatedLeconIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/lecon/$id': typeof AuthenticatedLeconIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/accueil' | '/admin' | '/lecon/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/accueil' | '/admin' | '/lecon/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accueil'
    | '/_authenticated/admin'
    | '/_authenticated/lecon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecon/$id': {
      id: '/_authenticated/lecon/$id'
      path: '/lecon/$id'
      fullPath: '/lecon/$id'
      preLoaderRoute: typeof AuthenticatedLeconIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLeconIdRoute: typeof AuthenticatedLeconIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLeconIdRoute: AuthenticatedLeconIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
